export const headings = {
  header: 'h1.heading',
  subheader: 'h2',
}

export const pageLinks = {
  abTesting: 'a[href="/abtest"]',
  addRemoveElements: 'a[href="/add_remove_elements/"]',
  basicAuth: 'a[href="/basic_auth"]',
  brokenImages: 'a[href="/broken_images"]',
  challengingDOM: 'a[href="/challenging_dom"]',
  checkboxes: 'a[href="/checkboxes"]',
  contextMenu: 'a[href="/context_menu"]',
  digestAuthentication: 'a[href="/digest_auth"]',
  disappearingElements: 'a[href="/disappearing_elements"]',
  dragAndDrop: 'a[href="/drag_and_drop"]',
  dropdown: 'a[href="/dropdown"]',
  dynamicContent: 'a[href="/dynamic_content"]',
  dynamicControls: 'a[href="/dynamic_controls"]',
  dynamicLoading: 'a[href="/dynamic_loading"]',
  entryAd: 'a[href="/entry_ad"]',
  exitIntent: 'a[href="/exit_intent"]',
  fileDownload: 'a[href="/download"]',
  fileUpload: 'a[href="/upload"]',
  floatingMenu: 'a[href="/floating_menu"]',
  forgotPassword: 'a[href="/forgot_password"]',
  formAuthentication: 'a[href="/login"]',
  frames: 'a[href="/frames"]',
  geolocation: 'a[href="/geolocation"]',
  horizontalSlider: 'a[href="/horizontal_slider"]',
  hovers: 'a[href="/hovers"]',
  infiniteScroll: 'a[href="/infinite_scroll"]',
  inputs: 'a[href="/inputs"]',
  jqueryUIMenu: 'a[href="/jqueryui/menu"]',
  javascriptAlerts: 'a[href="/javascript_alerts"]',
  javascriptOnloadError: 'a[href="/javascript_error"]',
  keyPresses: 'a[href="/key_presses"]',
  largeAndDeepDOM: 'a[href="/large"]',
  multipleWindows: 'a[href="/windows"]',
  nestedFrames: 'a[href="/nested_frames"]',
  notificationMessages: 'a[href="/notification_message"]',
  redirectLink: 'a[href="/redirector"]',
  secureFileDownload: 'a[href="/download_secure"]',
  shadowDOM: 'a[href="/shadowdom"]',
  shiftingContent: 'a[href="/shifting_content"]',
  slowResources: 'a[href="/slow"]',
  sortableDataTable: 'a[href="/tables"]',
  statusCodes: 'a[href="/status_codes"]',
  typos: 'a[href="/typos"]',
  wysiwygEditor: 'a[href="/tinymce"]',
}
